# Build state
FROM golang:1.20.5-alpine3.18 AS builder
WORKDIR /app
COPY . .
RUN apk add --no-cache make
RUN make build-api

FROM node:20.4-alpine3.17 AS client-builder
WORKDIR /app
COPY . .
WORKDIR /app/client
RUN npm install
RUN npm run build

# Run
FROM alpine:3.18
WORKDIR /app
RUN apk add --no-cache bash
COPY --from=builder /app/api-server .
COPY --from=client-builder /app/client/build /app/client/build
COPY app.env .
COPY wait-for-it.sh .

EXPOSE 8080
CMD [ "/app/api-server", "-r", "/app"]